name: Create release

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 10
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup PNPM
        uses: pnpm/action-setup@v4.1.0
        with:
          version: latest

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: package.json

      - name: Install standard-version
        run : pnpm i -g standard-version

      - name: Install dependencies
        run: pnpm install

      - name: Create migrations
        run: pnpm migration:create
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Config git
        run: |
          git config --global user.email "${{ github.event.sender.email }}"
          git config --global user.name "${{ github.event.sender.login }}"

      - name: Detect new migrations
        id: file_check
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          echo "Changed files: $CHANGED_FILES"
          if echo "$CHANGED_FILES" | grep -E '^drizzle/'; then
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit migrations
        if: steps.file_check.outputs.should_run == true
        run: |
          git add drizzle/
          git commit -m "chore(migrations): Add new migration"

      - name: Apply standard-version
        run: standard-version -t ""  --no-verify

      - name: Get new version
        id: version
        run: echo "VERSION=$(jq .version package.json -r)" >> $GITHUB_OUTPUT

      - name: Commit release
        run: |
          git checkout -b release/${{ steps.version.outputs.VERSION }}
          git push origin release/${{ steps.version.outputs.VERSION }}
          git push --tags

      - name: Create release PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
          --title "chore(release): ${{ steps.version.outputs.VERSION }}" \
          --body "chore(release): ${{ steps.version.outputs.VERSION }}" \
          --base main \
          --head release/${{ steps.version.outputs.VERSION }} \
          --label release